# Generated by Django 4.2.6 on 2023-10-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('technologies', models.CharField(max_length=255)),
                ('Project_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField()),
                ('image', models.ImageField(upload_to='project_images/')),
                ('completion_date', models.DateField()),
                ('achievements', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
