# Generated by Django 4.2.6 on 2023-10-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Project_url',
            new_name='project_url',
        ),
    ]
